version: "3.8"
services:
  psql:
    container_name: "postgres"
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: always

  nomades:
    container_name: "nomades"
    image: devsampaiodocker/nomades:main
    ports:
      - "8000:8000"
    depends_on:
      - psql
    restart: always

